"""Pydantic schemas."""
from app.schemas.auth import (
    AppleSignInRequest,
    EmailLoginRequest,
    EmailRegisterRequest,
    RefreshRequest,
    SignOutRequest,
    TokenResponse,
)
from app.schemas.dresser import (
    DrawerCreate,
    DrawerResponse,
    DrawerUpdate,
    DresserItemAdd,
    DresserItemMove,
    DresserItemResponse,
    DresserResponse,
    SharedDrawerResponse,
)
from app.schemas.product import ProductCard, ProductDetail, ProductResponse, SimilarProduct
from app.schemas.referral import (
    ApplyReferralCodeRequest,
    CompleteReferralRequest,
    LeaderboardEntry,
    LeaderboardResponse,
    ReferralCodeResponse,
    ReferralLinkResponse,
    ReferralRewardResponse,
    ReferralResponse,
    ReferralStatsResponse,
    RewardMilestoneResponse,
    ShareTrackingRequest,
)
from app.schemas.style_dna import StyleDNAResponse, StyleDNAShareResponse, StyleDNAStats
from app.schemas.swipe_event import SwipeEventBatch, SwipeEventCreate, SwipeEventResponse
from app.schemas.user import QuizSubmission, UserCreate, UserDetail, UserResponse, UserSettings, UserUpdate
from app.schemas.wallpaper import (
    WallpaperCurrentResponse,
    WallpaperHouseAnalyticsResponse,
    WallpaperHouseCreate,
    WallpaperHouseResponse,
    WallpaperHouseUpdate,
    WallpaperImpressionRequest,
    WallpaperPatternAnalyticsResponse,
    WallpaperPatternCreate,
    WallpaperPatternDetailResponse,
    WallpaperPatternResponse,
    WallpaperPatternUpdate,
)

__all__ = [
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    "UserDetail",
    "UserSettings",
    "QuizSubmission",
    "ProductResponse",
    "ProductDetail",
    "ProductCard",
    "SimilarProduct",
    "AppleSignInRequest",
    "EmailRegisterRequest",
    "EmailLoginRequest",
    "TokenResponse",
    "RefreshRequest",
    "SignOutRequest",
    "SwipeEventCreate",
    "SwipeEventBatch",
    "SwipeEventResponse",
    "DrawerCreate",
    "DrawerUpdate",
    "DrawerResponse",
    "DresserItemAdd",
    "DresserItemMove",
    "DresserItemResponse",
    "DresserResponse",
    "SharedDrawerResponse",
    "StyleDNAResponse",
    "StyleDNAShareResponse",
    "StyleDNAStats",
    "ReferralCodeResponse",
    "ReferralStatsResponse",
    "ReferralResponse",
    "ReferralRewardResponse",
    "LeaderboardEntry",
    "LeaderboardResponse",
    "ReferralLinkResponse",
    "ShareTrackingRequest",
    "ApplyReferralCodeRequest",
    "CompleteReferralRequest",
    "RewardMilestoneResponse",
    "WallpaperCurrentResponse",
    "WallpaperHouseCreate",
    "WallpaperHouseUpdate",
    "WallpaperHouseResponse",
    "WallpaperPatternCreate",
    "WallpaperPatternUpdate",
    "WallpaperPatternResponse",
    "WallpaperPatternDetailResponse",
    "WallpaperImpressionRequest",
    "WallpaperHouseAnalyticsResponse",
    "WallpaperPatternAnalyticsResponse",
]
